### ISSUE TITLE
typo in Make/options

### ISSUE THREAD

**Issue by EastEriq** [11101011/phaseFieldFoam-300#2]
https://github.com/11101011/phaseFieldFoam-300/blob/b21508b95835b98df7b5ed97ed6632326f72e18e/Make/options#L4

incompressible\lnInclude should be incompressible/lnInclude

**Comment by 11101011** [comment]
Indeed. Fixed by commit 9c8c6ef1cbe14cace4ef55fe23b7e343bb8bc468.

**Comment by EastEriq** [comment]
that was fast!
